name: deploy

on:
    push:
        branches: [master]
    pull_request:
        branches: [master]

jobs:
    build:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            pages: write
            id-token: write
        concurrency:
            group: ${{ github.workflow }}-${{ github.ref }}

        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Setup Pages
              uses: actions/configure-pages@v3

            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                node-version: 18.15.0

            - name: Get npm cache directory
              id: npm-cache-dir
              shell: bash
              run: echo "dir=$(npm config get cache)" >> ${GITHUB_OUTPUT}

            - name: Cache node modules
              uses: actions/cache@v3
              with:
                path: ${{ steps.npm-cache-dir.outputs.dir }}
                key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
                restore-keys: |
                  ${{ runner.os }}-node-

            - name: Install dependencies
              run: npm ci

            - name: Build project
              run: npm run build

            - name: Upload artifact
              uses: actions/upload-pages-artifact@v1
              with:
                path: './dist'

    deploy:
        runs-on: ubuntu-latest
        needs: build
        permissions:
            contents: read
            pages: write
            id-token: write

        environment:
            name: github-pages
            url: ${{ steps.deployment.outputs.page_url }}

        steps:
            - name: Deploy website
              if: ${{ github.ref == 'refs/heads/master' }}
              id: deployment
              uses: actions/deploy-pages@v1
